apiVersion: v1
kind: Service
metadata:
  name: etcdguardian-controller-manager-metrics-service
  namespace: etcd-guardian-system
  labels:
    app.kubernetes.io/name: etcdguardian
    app.kubernetes.io/component: controller
    control-plane: controller-manager
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: etcdguardian
    app.kubernetes.io/component: controller
    control-plane: controller-manager
