apiVersion: v1
kind: Secret
metadata:
  name: etcdguardian-webhook-tls
  namespace: etcd-guardian-system
  labels:
    app.kubernetes.io/name: etcdguardian
    app.kubernetes.io/component: security
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
