//go:build !ignore_autogenerated

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *NodeDiagnosticSpec) DeepCopyInto(out *NodeDiagnosticSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.NodeNames != nil {
		out.NodeNames = append([]string(nil), in.NodeNames...)
	}
	if in.Analyzers != nil {
		out.Analyzers = append([]string(nil), in.Analyzers...)
	}
	if in.ExcludeAnalyzers != nil {
		out.ExcludeAnalyzers = append([]string(nil), in.ExcludeAnalyzers...)
	}
	if in.Notify != nil {
		out.Notify = new(NotificationConfig)
		*out.Notify = *in.Notify
	}
}

func (in *NodeDiagnosticSpec) DeepCopy() *NodeDiagnosticSpec {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnosticSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeDiagnosticStatus) DeepCopyInto(out *NodeDiagnosticStatus) {
	*out = *in
	if in.StartTime != nil {
		out.StartTime = in.StartTime.DeepCopy()
	}
	if in.CompletionTime != nil {
		out.CompletionTime = in.CompletionTime.DeepCopy()
	}
	if in.NodeResults != nil {
		out.NodeResults = make([]NodeResult, len(in.NodeResults))
		for i := range in.NodeResults {
			in.NodeResults[i].DeepCopyInto(&out.NodeResults[i])
		}
	}
	if in.Conditions != nil {
		out.Conditions = append([]DiagnosticCondition(nil), in.Conditions...)
	}
}

func (in *NodeDiagnosticStatus) DeepCopy() *NodeDiagnosticStatus {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnosticStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeResult) DeepCopyInto(out *NodeResult) {
	*out = *in
	out.Summary = in.Summary
}

func (in *NodeResult) DeepCopy() *NodeResult {
	if in == nil {
		return nil
	}
	out := new(NodeResult)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterDiagnosticSpec) DeepCopyInto(out *ClusterDiagnosticSpec) {
	*out = *in
	if in.Analyzers != nil {
		out.Analyzers = append([]string(nil), in.Analyzers...)
	}
	if in.ExcludeAnalyzers != nil {
		out.ExcludeAnalyzers = append([]string(nil), in.ExcludeAnalyzers...)
	}
	if in.Notify != nil {
		out.Notify = new(NotificationConfig)
		*out.Notify = *in.Notify
	}
}

func (in *ClusterDiagnosticSpec) DeepCopy() *ClusterDiagnosticSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterDiagnosticSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
}

func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterDiagnosticStatus) DeepCopyInto(out *ClusterDiagnosticStatus) {
	*out = *in
	if in.StartTime != nil {
		out.StartTime = in.StartTime.DeepCopy()
	}
	if in.CompletionTime != nil {
		out.CompletionTime = in.CompletionTime.DeepCopy()
	}
	out.Summary = in.Summary
	if in.Conditions != nil {
		out.Conditions = append([]DiagnosticCondition(nil), in.Conditions...)
	}
}

func (in *ClusterDiagnosticStatus) DeepCopy() *ClusterDiagnosticStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterDiagnosticStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticSummary) DeepCopyInto(out *DiagnosticSummary) {
	*out = *in
}

func (in *DiagnosticSummary) DeepCopy() *DiagnosticSummary {
	if in == nil {
		return nil
	}
	out := new(DiagnosticSummary)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticCondition) DeepCopyInto(out *DiagnosticCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

func (in *DiagnosticCondition) DeepCopy() *DiagnosticCondition {
	if in == nil {
		return nil
	}
	out := new(DiagnosticCondition)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticScheduleSpec) DeepCopyInto(out *DiagnosticScheduleSpec) {
	*out = *in
	if in.ClusterDiagnosticTemplate != nil {
		out.ClusterDiagnosticTemplate = new(ClusterDiagnosticTemplate)
		in.ClusterDiagnosticTemplate.DeepCopyInto(out.ClusterDiagnosticTemplate)
	}
	if in.NodeDiagnosticTemplate != nil {
		out.NodeDiagnosticTemplate = new(NodeDiagnosticTemplate)
		in.NodeDiagnosticTemplate.DeepCopyInto(out.NodeDiagnosticTemplate)
	}
}

func (in *DiagnosticScheduleSpec) DeepCopy() *DiagnosticScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosticScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterDiagnosticTemplate) DeepCopyInto(out *ClusterDiagnosticTemplate) {
	*out = *in
	if in.Analyzers != nil {
		out.Analyzers = append([]string(nil), in.Analyzers...)
	}
	if in.ExcludeAnalyzers != nil {
		out.ExcludeAnalyzers = append([]string(nil), in.ExcludeAnalyzers...)
	}
	if in.Notify != nil {
		out.Notify = new(NotificationConfig)
		*out.Notify = *in.Notify
	}
}

func (in *ClusterDiagnosticTemplate) DeepCopy() *ClusterDiagnosticTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterDiagnosticTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeDiagnosticTemplate) DeepCopyInto(out *NodeDiagnosticTemplate) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.Analyzers != nil {
		out.Analyzers = append([]string(nil), in.Analyzers...)
	}
	if in.ExcludeAnalyzers != nil {
		out.ExcludeAnalyzers = append([]string(nil), in.ExcludeAnalyzers...)
	}
	if in.Notify != nil {
		out.Notify = new(NotificationConfig)
		*out.Notify = *in.Notify
	}
}

func (in *NodeDiagnosticTemplate) DeepCopy() *NodeDiagnosticTemplate {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnosticTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticScheduleStatus) DeepCopyInto(out *DiagnosticScheduleStatus) {
	*out = *in
	if in.LastRunTime != nil {
		out.LastRunTime = in.LastRunTime.DeepCopy()
	}
	if in.LastSuccessfulRun != nil {
		out.LastSuccessfulRun = in.LastSuccessfulRun.DeepCopy()
	}
	if in.Active != nil {
		out.Active = append([]corev1.ObjectReference(nil), in.Active...)
	}
	if in.Conditions != nil {
		out.Conditions = append([]DiagnosticCondition(nil), in.Conditions...)
	}
}

func (in *DiagnosticScheduleStatus) DeepCopy() *DiagnosticScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosticScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeDiagnostic) DeepCopyInto(out *NodeDiagnostic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NodeDiagnostic) DeepCopy() *NodeDiagnostic {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnostic)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeDiagnostic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NodeDiagnosticList) DeepCopyInto(out *NodeDiagnosticList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NodeDiagnostic, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *NodeDiagnosticList) DeepCopy() *NodeDiagnosticList {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnosticList)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeDiagnosticList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterDiagnostic) DeepCopyInto(out *ClusterDiagnostic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClusterDiagnostic) DeepCopy() *ClusterDiagnostic {
	if in == nil {
		return nil
	}
	out := new(ClusterDiagnostic)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterDiagnostic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterDiagnosticList) DeepCopyInto(out *ClusterDiagnosticList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ClusterDiagnostic, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ClusterDiagnosticList) DeepCopy() *ClusterDiagnosticList {
	if in == nil {
		return nil
	}
	out := new(ClusterDiagnosticList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterDiagnosticList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DiagnosticSchedule) DeepCopyInto(out *DiagnosticSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DiagnosticSchedule) DeepCopy() *DiagnosticSchedule {
	if in == nil {
		return nil
	}
	out := new(DiagnosticSchedule)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DiagnosticScheduleList) DeepCopyInto(out *DiagnosticScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DiagnosticSchedule, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *DiagnosticScheduleList) DeepCopy() *DiagnosticScheduleList {
	if in == nil {
		return nil
	}
	out := new(DiagnosticScheduleList)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
