apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcdguardian-manager-rolebinding
  labels:
    app.kubernetes.io/name: etcdguardian
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcdguardian-manager-role
subjects:
  - kind: ServiceAccount
    name: etcdguardian-controller-manager
    namespace: etcd-guardian-system
