apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcdguardian-controller-manager
  namespace: etcd-guardian-system
  labels:
    app.kubernetes.io/name: etcdguardian
    app.kubernetes.io/component: controller
automountServiceAccountToken: true
